version: "3.8"
services:
  client:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - server
    env_file:
      - ./client/.env

  server:
    build: ./server
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - ./server/.env
