export const SECOND_TO_MILLISECOND = 1_000
export const MINUTE_TO_SECOND = 60
export const HOUR_TO_MINUTE = 60

export const MINUTE_TO_MILLISECOND = MINUTE_TO_SECOND * SECOND_TO_MILLISECOND
export const HOUR_TO_MILLISECOND = HOUR_TO_MINUTE * MINUTE_TO_MILLISECOND
